### ISSUE TITLE
Add suport for interlaced content (1080i)

### ISSUE THREAD

**Issue by tobiasglen** [platelminto/parse-torrent-title#24]
PTN can parse common resolutions like 1080p and 720p easily enough but won't match interlaced content like 1080i

an example of a torrent title using interlacing:
Extraterrestrial.2011.BluRay.1080i.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR.mkv

**Comment by platelminto** [comment]
Fixed in 2.3
