### ISSUE TITLE
Not correctly parsing title from [Title][Season][Episode][Episode]

### ISSUE THREAD

**Issue by Coloradohusky** [platelminto/parse-torrent-title#31]
Parsing `The.Amazing.World.Of.Gumball.S04E41E42.720p.WEB-DL.AAC2.0.H.264-IT00NZ.mkv` is returning the following:
`{'episode': 41, 'resolution': '720p', 'quality': 'WEB-DL', 'codec': 'H.264', 'audio': 'AAC 2.0', 'container': 'MKV', 'title': 'The Amazing World Of Gumball S04', 'excess': 'E42', 'encoder': 'IT00NZ'}`
As you can see, the title says `The Amazing World Of Gumball S04` instead of `The Amazing World Of Gumball`. Also, the season is missing.
Tested it with just `The.Amazing.World.Of.Gumball.S04` and with `The.Amazing.World.Of.Gumball.S04E41` and it works fine.

**Comment by platelminto** [comment]
This is fixed on the dev branch, you can either wait for the new release, or run

`pip install git+https://github.com/platelminto/parse-torrent-title.git@dev`

New release should be soon.

**Comment by Coloradohusky** [comment]
Awesome, thanks! If there are future viewers of this thread, make sure to `pip uninstall parse-torrent-title` first, because otherwise it won't install due to the versions being the same (2.3).
