### ISSUE TITLE
Add ability to parse subtitle names

### ISSUE THREAD

**Issue by astro-stan** [platelminto/parse-torrent-title#33]
After a quick glance of the source code, I believe this should not be very hard to add, but I could be wrong.

My suggestion for implementing this would be to check the end of the name for an ISO-639-1 (2-letter) or ISO-639-2/B (3-letter) language name or a language name + keyword (forced, sdh, etc). If none of those are present and the file extension (if provided) is not for a subtitle file, then the name can be parsed as usual.

Examples:
```
A.Movie.2021.1080p.bluray.x264-xxx.en.srt
A.Movie.2021.1080p.bluray.x264-xxx.eng.sub
A.Movie.2021.1080p.bluray.x264-xxx.eng.forced.ssa
A.Movie.2021.1080p.bluray.x264-xxx.eng.sdh.srt

A.Series.2021.s01e01.1080p.bluray.x264-xxx.en.srt
A.Series.2021.s01e01.1080p.bluray.x264-xxx.eng.sub
A.Series.2021.s01e01.1080p.bluray.x264-xxx.eng.forced.ssa
A.Series.2021.s01e01.1080p.bluray.x264-xxx.eng.sdh.srt
```

**Comment by platelminto** [comment]
Thanks for opening an issue!

I'll definitely be looking to add subtitle file extensions (might add a `file-type` field, possibly replacing `container`).

The (admittedly, few) examples I've seen simply copy the video title, the only difference being the file extension. Do you have any real examples, or a place to find them, that are similar to the examples you provided? This would help with knowing which subtitle categories to look for (from your examples, "forced" and "sdh"), so I can see if/what new fields will be necessary. The language seems to work fine regardless, using what's already there.

**Comment by platelminto** [comment]
I've pushed some initial work towards this on the `dev` branch. 

`container` is now `filetype`, and includes support for srt, sub, and ssa. There are some issues with sub (the `subtitles` field gets filled), but this is more related to #19.
